/**
 * Stores & products kit: product cards, stock, categories, store locations.
 * Uses shared UI (Card, Badge, Table). Import from here for store/product management.
 */
export { StockLevel } from './StockLevel'
export type { StockLevelProps, StockStatus } from './StockLevel'
export { PriceDisplay } from './PriceDisplay'
export type { PriceDisplayProps } from './PriceDisplay'
export { CategoryChip } from './CategoryChip'
export type { CategoryChipProps } from './CategoryChip'
export { ProductCard } from './ProductCard'
export type { ProductCardProps } from './ProductCard'
export { ProductCardCompact } from './ProductCardCompact'
export type { ProductCardCompactProps } from './ProductCardCompact'
export { ProductCardFeature } from './ProductCardFeature'
export type { ProductCardFeatureProps } from './ProductCardFeature'
export { SaleCard } from './SaleCard'
export type { SaleCardProps } from './SaleCard'
export { ProductCarousel } from './ProductCarousel'
export type { ProductCarouselProps, ProductCarouselItem } from './ProductCarousel'
export { ProductTable } from './ProductTable'
export type { ProductTableProps, ProductRow } from './ProductTable'
export { StoreLocationCard } from './StoreLocationCard'
export type { StoreLocationCardProps, StoreStatus } from './StoreLocationCard'
export { LowStockBanner } from './LowStockBanner'
export type { LowStockBannerProps } from './LowStockBanner'
export { MapPlaceholder } from './MapPlaceholder'
export type { MapPlaceholderProps } from './MapPlaceholder'
export { LocationSearchBar } from './LocationSearchBar'
export type { LocationSearchBarProps } from './LocationSearchBar'
export { LocationSummaryCard } from './LocationSummaryCard'
export type { LocationSummaryCardProps } from './LocationSummaryCard'
